version: '3.7'

x-es-logging:
  &es-logging
  options:
    max-size: '300m'
    max-file: '2'
  driver: json-file

x-standard-logging:
  &service-logging
  options:
    max-size: '500m'
    max-file: '3'
  driver: json-file

x-ui-logging:
  &ui-logging
  options:
    max-size: '100m'
    max-file: '3'
  driver: json-file

services:
  indyscan-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: indyscan-elasticsearch
    logging: *es-logging
    networks:
      - esnet
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - indyscan-es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  indyscan-kibana:
    container_name: indyscan-kibana
    image: docker.elastic.co/kibana/kibana:7.6.1
    logging: *es-logging
    networks:
      - esnet
    environment:
      - ELASTICSEARCH_HOSTS=http://indyscan-elasticsearch.esnet:9200
    ports:
      - 5601:5601
    depends_on:
      - indyscan-elasticsearch
#
  indyscan-daemon:
    restart: unless-stopped
    image: pstas/indyscan-daemon:4.1.0
    container_name: indyscan-daemon
    logging: *service-logging
    depends_on:
      - indyscan-elasticsearch
    networks:
      - esnet
      - affirmatios_agent_net
    environment:
      - WORKER_CONFIGS=/home/indyscan/indyscan-daemon/app-configs-docker/INDYSCANPOOL.json
      - LOG_LEVEL=info
      - LOG_HTTP_REQUESTS=true
      - LOG_HTTP_RESPONSES=true
      - SERVER_ENABLED=true
      - SERVER_PORT=3709
      - AUTOSTART=true
      - ENABLE_LOGFILES=false
    volumes:
      - ./app-configs-daemon/:/home/indyscan/indyscan-daemon/app-configs-docker

  indyscan-api:
    restart: unless-stopped
    image: pstas/indyscan-api:4.1.0
    container_name: indyscan-api
    logging: *service-logging
    environment:
      - NETWORKS_CONFIG_PATH=/home/indyscan/indyscan-api/app-config-docker/localhost.json
      - ES_URL=http://indyscan-elasticsearch.esnet:9200
      - AUTOSTART=true
      - LOG_LEVEL=debug
      - PORT=3708
      - LOG_HTTP_REQUESTS=true
      - LOG_HTTP_RESPONSES=true
    networks:
      - affirmatios_agent_net
      - esnet
    ports:
      - 3708:3708
    volumes:
      - ./app-config-api/:/home/indyscan/indyscan-api/app-config-docker

  indyscan-webapp:
    restart: unless-stopped
    image: pstas/indyscan-webapp:4.1.0
    container_name: indyscan-webapp
    logging: *ui-logging
    environment:
      - INDYSCAN_API_URL=http://indyscan-api.affirmatios_agent_net:3708
      - DAEMON_WS_URL=http://indyscan-daemon.affirmatios_agent_net:3709
      - PORT=3707
      - LOG_LEVEL=warn
      - LOG_HTTP_REQUESTS=false
      - LOG_HTTP_RESPONSES=false
    networks:
      - affirmatios_agent_net
    ports:
      - 3707:3707

  indyscan-daemon-ui:
    restart: unless-stopped
    image: pstas/indyscan-daemon-ui:4.1.0
    container_name: indyscan-daemon-ui
    logging: *ui-logging
    environment:
      - PORT=3710
      - PROXY_API_URL=http://indyscan-daemon.affirmatios_agent_net:3709
      - CHOKIDAR_USEPOLLING=true
    networks:
      - affirmatios_agent_net
    ports:
      - 3710:3710

networks:
  affirmatios_agent_net:
    external: true
  esnet:
    name: esnet
    driver: bridge

volumes:
  indyscan-es:
    driver: local
  affirmatios_agent_volumes:
    external: true
